### ISSUE TITLE
'Nifti1Header' object has no attribute '_structarr' upon copy

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nibabel#144]
As reported originally on nipy-user
https://groups.google.com/forum/?fromgroups=#!topic/nipy-user/tDl4w2oN75U

```
    header_ = evds.a.imghdr.copy()
  File "/usr/lib/pymodules/python2.6/nibabel/nifti1.py", line 561, in copy
    self.binaryblock,
  File "/usr/lib/pymodules/python2.6/nibabel/wrapstruct.py", line 210, in binaryblock
    return self._structarr.tostring()
AttributeError: 'Nifti1Header' object has no attribute '_structarr'
```

and it is probably related to the trigger -- storing of this header into hdf5 using our PyMVPA hdf5 backend under nibabel 1.2.0 and then reloading it with nibabel 1.4.0, so per se it might not even be nibabel's issue... but that yet to be proven ;)

**Comment by bcipolli** [comment]
@yarikoptic I am hitting this same issue, using nibabel v2.0.0 and trying to access data from http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/ .

Did you find a workaround for this?

**Comment by yarikoptic** [comment]
@bcipolli unfortunately I must just ask your forgiveness for our somewhat obnoxious way to serialize everything and anything into HDF5 -- it simply often doesn't work across versions (save with one, load with another) of external (or "internal" ;)) modules providing classes without proper serialization methods.

So the only current remedy to still stick to previous nibabel 1.3.0 while loading this dataset... hopefully we provide a workaround some time soonish

**Comment by bcipolli** [comment]
@yarikoptic I really appreciate the note.  I was able to get this to work with nibabel v1.0, but not v1.2 nor v1.3.  Just FYI :)

**Comment by yarikoptic** [comment]
@bcipolli that is strange:

```
hopa:/tmp
$> wget -c http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/hyperalignment_tutorial_data.hdf5.gz
--2015-02-21 22:53:55--  http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/hyperalignment_tutorial_data.hdf5.gz
Resolving data.pymvpa.org (data.pymvpa.org)... 129.170.30.193
Connecting to data.pymvpa.org (data.pymvpa.org)|129.170.30.193|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14252520 (14M) [application/x-gzip]
Saving to: ‘hyperalignment_tutorial_data.hdf5.gz’

hyperalignment_tutorial_data.hdf5.gz   100%[=============================================================================>]  13.59M  3.35MB/s   in 4.3s   

2015-02-21 22:53:59 (3.18 MB/s) - ‘hyperalignment_tutorial_data.hdf5.gz’ saved [14252520/14252520]


#2 !61 [0].....................................:Sat Feb 21 22:53:59:.
hopa:/tmp
$> apt-cache policy python-nibabel
python-nibabel:
  Installed: 1.3.0-2
  Candidate: 1.3.0-2
  Version table:
     2.0.0-1~nd80+1 0
        500 http://neuro.debian.net/debian-devel/ jessie/main amd64 Packages
 *** 1.3.0-2 0
        900 http://http.debian.net/debian/ jessie/main amd64 Packages
        600 http://http.debian.net/debian/ sid/main amd64 Packages
        100 /var/lib/dpkg/status
     1.3.0-1~nd70+1 0
        500 http://neuro.debian.net/debian/ jessie/main amd64 Packages

#3 !62 [0].....................................:Sat Feb 21 22:54:06:.
hopa:/tmp
$> python -c 'from mvpa2.base.hdf5 import h5load; print h5load("hyperalignment_tutorial_data.hdf5.gz")'  | head
[Dataset(array([[-0.01163818, -0.01163818,  0.00453591, ...,  0.06999348,
         0.26156655,  0.03828176],
       [-0.00443326, -0.00443326,  0.0033065 , ..., -0.00524773,
        -0.00151256, -0.03147409],
       [-0.01418352, -0.01418352,  0.00432815, ..., -0.00598793,
        -0.07479344, -0.15036383],
       ..., 
       [-0.00061614, -0.00061614,  0.00977637, ..., -0.00502579,
         0.05680206,  0.0594268 ],
       [ 0.0056519 ,  0.0056519 ,  0.00902873, ..., -0.00473931,
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 32] Broken pipe

#4 !63 [0].....................................:Sat Feb 21 22:54:19:.
hopa:/tmp
$> md5sum hyperalignment_tutorial_data.hdf5.gz 
e701480c76c07ea060d4223019a84acc  hyperalignment_tutorial_data.hdf5.gz
```

**Comment by yarikoptic** [comment]
what is your pymvpa version btw?  mine is 2.3.1-2  and IIRC we had some fixes related to workarounds in 2.3.0

**Comment by bcipolli** [comment]
2.3.1.  The dataset loads fine for me, but I can't access `dataset[0].a.imghdr` (except for when I have nibabel v1.0)

**Comment by effigies** [comment]
Some deep thread necromancy, but is this still an issue? A minimal reproducible example would be great. I see @yarikoptic's suggestion of providing `__reduce__` (or `__reduce_ex__` I guess...), but without a round-trip test that fails, it would be a pain.
